services:
  backend:
    environment:
      ENV: development
    image: ghcr.io/astral-sh/uv:python3.12-bookworm
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app/server
      - ./server/pyproject.toml:/app/pyproject.toml
      - ./server/uv.lock:/app/uv.lock

    entrypoint: >
      sh -c "
      uv sync &&
      exec uv run uvicorn server.fastapi_api.main:app --host 0.0.0.0 --port 8000 --reload
      "

  frontend:
    environment:
      VITE_BACKEND_URI: http://localhost:8000
    image: node:20
    working_dir: /app/client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules   # prevents host node_modules override
    command: sh -c "npm install && npm run dev -- --host"
